rendezvous_server = 'rustdesk.sidcorp.co:21116'
nat_type = 2
serial = 0
unlock_pin = ''
trusted_devices = '00NiekjdCiuuQuXCPQqNPw9s9b'

[options]
av1-test = 'Y'
local-ip-addr = '192.168.1.8'
key = '6CkfuxXeizUJ4KSnRzq8BgziL5+sMZTVAu+kGNbtFoI='
custom-rendezvous-server = 'rustdesk.sidcorp.co'
